module.exports = {
  someSidebar: {
    'Introduction': ['getting_started','hardware'],
    'Firmware': ['features',
                  'firmware/firmware_intro',
                  'firmware/hardware_api',
                  'firmware/keymap_api',
                  'firmware/keyboard_loop'],
    'Keyboards/Macropads': ['hardware/4x4macropad',
                 'hardware/5x5macropad',
                 'hardware/gridmx47',
                 'hardware/offsetmx43',
                 'hardware/pykey60'],
    'Testing Hardware': ['testing_hardware/basic',
                 'testing_hardware/encoders',
                 'testing_hardware/analog',
                 'testing_hardware/keymatrix',
                 'testing_hardware/findingbuttons',
                 'testing_hardware/findingmatrix',
                 'testing_hardware/neopixels',
                 'testing_hardware/sound',
                 'testing_hardware/sleep'],
   'Setup': ['setup/libraries'],
   'EncoderPad': ['encoderpad/compared']
  },
};
